language: node_js
node_js:
    - "0.10"
    - "0.11"
before_script:
    - npm install -g mocha
notifications:
    slack:
        rooms:
            - secure: "Qk4p9Lj+g1a4OfQqVO0NXLblqK35ayZb/AEf/v/Tr0K9aA1bUSTISXPU7c9tGQdtE3yYhYk4/48GeIbqd6mvQDtxJZy3QPuLUnythfGZA6xy0OCG/kFrHbq90w88JrYvNwVuMZunJvUmwwM4KltY4wudnQa/BT0YXyfTGPU8Yes=" 
